import { Injectable, NotFoundException } from "@nestjs/common";
import PDFDocument from "pdfkit";
import { PrismaService } from "prisma/prisma.service";

@Injectable()
export class PdfService {
    constructor(private readonly prisma: PrismaService) { };

    async generateDiagnosisPDF(user_id: string) {
        const user = await this.prisma.users.findUnique({
            where: { id: BigInt(user_id) },
            include: {
                health: true,
            }
        });

        const diagnosis = await this.prisma.health_prediction.findFirst({
            where: {
                health: { user_id: BigInt(user_id) }
            },
            orderBy: { created_at: 'desc' }
        });

        const healthResult = await this.prisma.health.findFirst({
            where: {
                user_id: BigInt(user_id)
            },
            orderBy: { recorded_at: 'desc' }
        });

        if (!user) throw new NotFoundException('User not found!');
        if (!diagnosis) throw new NotFoundException('Diagnosis record is not found!');
        if (!healthResult) throw new NotFoundException('Health record is not found!');

        return new Promise((resolve) => {
            const doc = new PDFDocument({ margin: 50 });
            const chunks: Buffer[] = [];

            doc.on('data', (chunk) => chunks.push(chunk));
            doc.on('end', () => resolve(Buffer.concat(chunks)));

            doc.fontSize(25).text('Medical Diagnosis Report', { align: 'center' });
            doc.moveDown();
            doc.fontSize(12).text(`Date: ${diagnosis?.created_at?.toLocaleDateString()}`);

            doc.moveDown();

            doc.fontSize(14).text(`Patient Information:`);
            doc.fontSize(12).text(`Name: ${user?.name}`);

            doc.fontSize(14).text(`Health Information:`);
            doc.fontSize(12).text(`Age: ${healthResult?.age}`);
            doc.fontSize(12).text(`Sex: ${healthResult?.sex}`);
            doc.fontSize(12).text(`Chest Pain: ${healthResult?.cp}`);
            doc.fontSize(12).text(`Blood Pressure: ${healthResult?.trestbps}`);
            doc.fontSize(12).text(`Cholesterol: ${healthResult?.chol}`);
            doc.fontSize(12).text(`Fasting Blood Sugar: ${healthResult?.fbs}`);
            doc.fontSize(12).text(`Resting Electrocardiogram: ${healthResult?.restecg}`);
            doc.fontSize(12).text(`Maximum Heart Rate: ${healthResult?.thalach}`);
            doc.fontSize(12).text(`Exercise Induced Angina: ${healthResult?.exang}`);
            doc.fontSize(12).text(`ST Depression: ${healthResult?.oldpeak}`);
            doc.fontSize(12).text(`Slope: ${healthResult?.slope}`);
            doc.fontSize(12).text(`Number of Vessels: ${healthResult?.ca}`);
            doc.fontSize(12).text(`Thalassemia: ${healthResult?.thal}`);

            doc.moveDown();
            doc.fontSize(14).text(`Prediction Results:`);
            doc.fontSize(12).text(`Risk Score: ${diagnosis?.risk_score}`);
            doc.fontSize(12).text(`Band: ${diagnosis?.band}`);
            doc.fontSize(10).fillColor('gray').text(`Disclaimer: This report is generated by an AI model for educational support. It does not replace professional medical advice.`)

            doc.end();
        });
    }
}